export const SUPER_ACCOUNT_MODAL_ADD = 'SUPER_ACCOUNT_MODAL_ADD';
export const SUPER_ACCOUNT_MODAL_EDIT = 'SUPER_ACCOUNT_MODAL_EDIT';
export const SUPER_ACCOUNT_MODAL_HIDE = 'SUPER_ACCOUNT_MODAL_HIDE';