export const ABNOR_METER_TABLE_UPDATE = 'ABNOR_METER_TABLE_UPDATE';
export const ABNOR_METER_TABLE_LOADING = 'ABNOR_METER_TABLE_LOADING';
export const ABNOR_METER_CHANGE_PAGINATION = 'ABNOR_METER_CHANGE_PAGINATION';
export const ABNOR_METER_CHANGE_TYPE = 'ABNOR_METER_CHANGE_TYPE';
export const ABNOR_METER_CHANGE_VALUE = 'ABNOR_METER_CHANGE_VALUE';