export const ADMIN_HEADER_CHANGE_TYPE = 'ADMIN_HEADER_CHANGE_TYPE';
export const ADMIN_HEADER_CHANGE_VALUE = 'ADMIN_HEADER_CHANGE_VALUE';
export const ADMIN_HEADER_CHANGE_STATE = 'ADMIN_HEADER_CHANGE_STATE';
export const ADMIN_HEADER_CHANGE_ENABLE = 'ADMIN_HEADER_CHANGE_ENABLE';
export const ADMIN_HEADER_CHANGE_BIND = 'ADMIN_HEADER_CHANGE_BIND';
export const ADMIN_HEADER_CHANGE_PAGINATION = 'ADMIN_HEADER_CHANGE_PAGINATION';