export const USER_RENTLOG_TABLE_UPDATE = 'USER_RENTLOG_TABLE_UPDATE';
export const USER_RENTLOG_TABLE_LOADING = 'USER_RENTLOG_TABLE_LOADING';
export const USER_RENTLOG_CHANGE_PAGINATION = 'USER_RENTLOG_CHANGE_PAGINATION';