export const FLOWSTATISTIC_TABLE_UPDATE = 'FLOWSTATISTIC_TABLE_UPDATE';
export const FLOWSTATISTIC_TABLE_LOADING = 'FLOWSTATISTIC_TABLE_LOADING';
export const FLOWSTATISTIC_CHANGE_PAGINATION = 'FLOWSTATISTIC_CHANGE_PAGINATION';
export const FLOWSTATISTIC_CHANGE_TIME = 'FLOWSTATISTIC_CHANGE_TIME';
export const FLOWSTATISTIC_CHANGE_PWY = 'FLOWSTATISTIC_CHANGE_PWY';
export const FLOWSTATISTIC_CHANGE_DIR = 'FLOWSTATISTIC_CHANGE_DIR';
export const FLOWSTATISTIC_CHANGE_TYPE = 'FLOWSTATISTIC_CHANGE_TYPE';
export const FLOWSTATISTIC_CHANGE_VALUE = 'FLOWSTATISTIC_CHANGE_VALUE';