export const AGENT_HEADER_CHANGE_TYPE = 'AGENT_HEADER_CHANGE_TYPE';
export const AGENT_HEADER_CHANGE_VALUE = 'AGENT_HEADER_CHANGE_VALUE';
export const AGENT_HEADER_CHANGE_STATE = 'AGENT_HEADER_CHANGE_STATE';
export const AGENT_HEADER_CHANGE_ENABLE = 'AGENT_HEADER_CHANGE_ENABLE';
export const AGENT_HEADER_CHANGE_BIND = 'AGENT_HEADER_CHANGE_BIND';
export const AGENT_HEADER_CHANGE_PAGINATION = 'AGENT_HEADER_CHANGE_PAGINATION';