export const SUPER_ACCOUNT_HEADER_CHANGE_TYPE = 'SUPER_ACCOUNT_HEADER_CHANGE_TYPE';
export const SUPER_ACCOUNT_HEADER_CHANGE_VALUE = 'SUPER_ACCOUNT_HEADER_CHANGE_VALUE';
export const SUPER_ACCOUNT_HEADER_CHANGE_STATE = 'SUPER_ACCOUNT_HEADER_CHANGE_STATE';
export const SUPER_ACCOUNT_HEADER_CHANGE_ENABLE = 'SUPER_ACCOUNT_HEADER_CHANGE_ENABLE';
export const SUPER_ACCOUNT_HEADER_CHANGE_BIND = 'SUPER_ACCOUNT_HEADER_CHANGE_BIND';
export const SUPER_ACCOUNT_HEADER_CHANGE_PAGINATION = 'SUPER_ACCOUNT_HEADER_CHANGE_PAGINATION';