export const SWITCH_HEADER_CHANGE_TYPE = 'SWITCH_HEADER_CHANGE_TYPE';
export const SWITCH_HEADER_CHANGE_VALUE = 'SWITCH_HEADER_CHANGE_VALUE';
export const SWITCH_HEADER_CHANGE_STATE = 'SWITCH_HEADER_CHANGE_STATE';
export const SWITCH_HEADER_CHANGE_ENABLE = 'SWITCH_HEADER_CHANGE_ENABLE';
export const SWITCH_HEADER_CHANGE_BIND = 'SWITCH_HEADER_CHANGE_BIND';
export const SWITCH_HEADER_CHANGE_PAGINATION = 'SWITCH_HEADER_CHANGE_PAGINATION';