export const USER_HEADER_CHANGE_TYPE = 'USER_HEADER_CHANGE_TYPE';
export const USER_HEADER_CHANGE_VALUE = 'USER_HEADER_CHANGE_VALUE';
export const USER_HEADER_CHANGE_STATE = 'USER_HEADER_CHANGE_STATE';
export const USER_HEADER_CHANGE_ENABLE = 'USER_HEADER_CHANGE_ENABLE';
export const USER_HEADER_CHANGE_BIND = 'USER_HEADER_CHANGE_BIND';
export const USER_HEADER_CHANGE_PAGINATION = 'USER_HEADER_CHANGE_PAGINATION';