export const RECHARGELOG_TABLE_UPDATE = 'RECHARGELOG_TABLE_UPDATE';
export const RECHARGELOG_TABLE_LOADING = 'RECHARGELOG_TABLE_LOADING';
export const RECHARGELOG_CHANGE_PAGINATION = 'RECHARGELOG_CHANGE_PAGINATION';