export const ELECTSTATISTIC_TABLE_UPDATE = 'ELECTSTATISTIC_TABLE_UPDATE';
export const ELECTSTATISTIC_TABLE_LOADING = 'ELECTSTATISTIC_TABLE_LOADING';
export const ELECTSTATISTIC_CHANGE_PAGINATION = 'ELECTSTATISTIC_CHANGE_PAGINATION';
