export const METER_TABLE_UPDATE = 'METER_TABLE_UPDATE';
export const METER_TABLE_LOADING = 'METER_TABLE_LOADING';
export const METER_TABLE_SELECT_ROWS = 'METER_TABLE_SELECT_ROWS';
export const METER_TABLE_BATCH_OPERATION='METER_TABLE_BATCH_OPERATION';