export const USER_DEVS_TABLE_UPDATE = 'USER_DEVS_TABLE_UPDATE';
export const USER_DEVS_TABLE_LOADING = 'USER_DEVS_TABLE_LOADING';
export const USER_DEVS_CHANGE_PAGINATION = 'USER_DEVS_CHANGE_PAGINATION';
export const USER_DEVS_CHANGE_TYPE = 'USER_DEVS_CHANGE_TYPE';