export const COLLECT_INFO_HEADER_CHANGE_TYPE = 'COLLECT_INFO_HEADER_CHANGE_TYPE';
export const COLLECT_INFO_HEADER_CHANGE_VALUE = 'COLLECT_INFO_HEADER_CHANGE_VALUE';
export const COLLECT_INFO_HEADER_CHANGE_STATE = 'COLLECT_INFO_HEADER_CHANGE_STATE';
export const COLLECT_INFO_HEADER_CHANGE_ENABLE = 'COLLECT_INFO_HEADER_CHANGE_ENABLE';
export const COLLECT_INFO_HEADER_CHANGE_BIND = 'COLLECT_INFO_HEADER_CHANGE_BIND';
export const COLLECT_INFO_HEADER_CHANGE_PAGINATION = 'COLLECT_INFO_HEADER_CHANGE_PAGINATION';