export const GROUP_HEADER_CHANGE_TYPE = 'GROUP_HEADER_CHANGE_TYPE';
export const GROUP_HEADER_CHANGE_VALUE = 'GROUP_HEADER_CHANGE_VALUE';
export const GROUP_HEADER_CHANGE_STATE = 'GROUP_HEADER_CHANGE_STATE';
export const GROUP_HEADER_CHANGE_ENABLE = 'GROUP_HEADER_CHANGE_ENABLE';
export const GROUP_HEADER_CHANGE_BIND = 'GROUP_HEADER_CHANGE_BIND';
export const GROUP_HEADER_CHANGE_PAGINATION = 'GROUP_HEADER_CHANGE_PAGINATION';