export const BOOK_PROFEE_HEADER_CHANGE_TYPE = 'BOOK_PROFEE_HEADER_CHANGE_TYPE';
export const BOOK_PROFEE_HEADER_CHANGE_EXPIRE = 'BOOK_PROFEE_HEADER_CHANGE_EXPIRE';
export const BOOK_PROFEE_HEADER_CHANGE_VALUE = 'BOOK_PROFEE_HEADER_CHANGE_VALUE';
export const BOOK_PROFEE_HEADER_CHANGE_STATE = 'BOOK_PROFEE_HEADER_CHANGE_STATE';
export const BOOK_PROFEE_HEADER_CHANGE_ENABLE = 'BOOK_PROFEE_HEADER_CHANGE_ENABLE';
export const BOOK_PROFEE_HEADER_CHANGE_BIND = 'BOOK_PROFEE_HEADER_CHANGE_BIND';
export const BOOK_PROFEE_HEADER_CHANGE_PAGINATION = 'BOOK_PROFEE_HEADER_CHANGE_PAGINATION';