export const PARAM_HEADER_CHANGE_TYPE = 'PARAM_HEADER_CHANGE_TYPE';
export const PARAM_HEADER_CHANGE_VALUE = 'PARAM_HEADER_CHANGE_VALUE';
export const PARAM_HEADER_CHANGE_STATE = 'PARAM_HEADER_CHANGE_STATE';
export const PARAM_HEADER_CHANGE_ENABLE = 'PARAM_HEADER_CHANGE_ENABLE';
export const PARAM_HEADER_CHANGE_BIND = 'PARAM_HEADER_CHANGE_BIND';
export const PARAM_HEADER_CHANGE_PAGINATION = 'PARAM_HEADER_CHANGE_PAGINATION';